### ISSUE TITLE
Build failing starting 2023-07-17

### ISSUE THREAD

**Issue by jonbwhite** [mdegis/bandit-action#1]
```
Build container for action use: '/home/runner/work/_actions/mdegis/bandit-action/v1.0/Dockerfile'.
  /usr/bin/docker build -t c9a4a5:64e7717af3f34889a59b8115e175c96[2](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:2) -f "/home/runner/work/_actions/mdegis/bandit-action/v1.0/Dockerfile" "/home/runner/work/_actions/mdegis/bandit-action/v1.0"
  Sending build context to Docker daemon  [3](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:3).73[4](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:4)MB
  
  Step 1/7 : FROM python:3.9-alpine
  3.9-alpine: Pulling from library/python
  31e3[5](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:5)2740f53: Already exists
  cfcc27[6](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:6)e4459: Pulling fs layer
  baaf5[7](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:7)0[8](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:8)5[9](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:9)b3: Pulling fs layer
  7523d885c165: Pulling fs layer
  7d3b4e992056: Pulling fs layer
  7d3b4e992056: Waiting
  7523d885c165: Verifying Checksum
  7523d885c165: Download complete
  cfcc276e4459: Verifying Checksum
  cfcc276e4459: Download complete
  baaf570859b3: Verifying Checksum
  baaf570859b3: Download complete
  7d3b4e992056: Verifying Checksum
  7d3b4e992056: Download complete
  cfcc276e4459: Pull complete
  baaf570859b3: Pull complete
  7523d885c165: Pull complete
  7d3b4e992056: Pull complete
  Digest: sha256:2e94e493d6d50[10](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:10)d739ea473e44ea40f7c6e168bcb78e0c5a48c64f06aafbf5f
  Status: Downloaded newer image for python:3.9-alpine
   ---> d56c84cce2aa
  Step 2/7 : WORKDIR /app
   ---> Running in 3acd2e549226
  Removing intermediate container 3acd2e549226
   ---> 78d4afc82918
  Step 3/7 : COPY dist/bandit-github-formatter-1.0.tar.gz bandit-github-formatter-1.0.tar.gz
   ---> 0493fb61fe23
  Step 4/7 : RUN pip install bandit==1.7.0 requests==2.25.1 bandit-github-formatter-1.0.tar.gz
   ---> Running in 8e25785c6414
  Processing ./bandit-github-formatter-1.0.tar.gz
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Collecting bandit==1.7.0
    Downloading bandit-1.7.0-py3-none-any.whl ([11](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:11)5 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.2/115.2 kB 5.3 MB/s eta 0:00:00
  Collecting requests==2.25.1
    Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 13.9 MB/s eta 0:00:00
  Collecting GitPython>=1.0.1
    Downloading GitPython-3.1.32-py3-none-any.whl (188 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.5/188.5 kB 32.3 MB/s eta 0:00:00
  Collecting six>=1.10.0
    Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
  Collecting stevedore>=1.20.0
    Downloading stevedore-5.1.0-py3-none-any.whl (49 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 11.4 MB/s eta 0:00:00
  Collecting PyYAML>=5.3.1
    Downloading PyYAML-6.0.tar.gz ([12](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:12)4 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 22.3 MB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [48 lines of output]
        running egg_info
        writing lib/PyYAML.egg-info/PKG-INFO
        writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
        writing top-level names to lib/PyYAML.egg-info/top_level.txt
        Traceback (most recent call last):
          File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 288, in <module>
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 3[14](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:14), in run
            self.find_sources()
          File "/tmp/pip-build-env-mhhe[22](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:22)bf/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
            mm.run()
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 551, in run
            self.add_defaults()
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
            sdist.add_defaults(self)
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
            super().add_defaults()
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
            self._add_defaults_ext()
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
            self.filelist.extend(build_ext.get_source_files())
          File "<string>", line 204, in get_source_files
          File "/tmp/pip-build-env-mhhe22bf/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  
  Notice:  A new release of pip is available: [23](https://github.com/withmultiply/multiply_web/actions/runs/5580738834/jobs/10198204811#step:2:23).0.1 -> 23.2
  Notice:  To update, run: pip install --upgrade pip
```

**Comment by mdegis** [comment]
I think this is about the https://github.com/yaml/pyyaml/issues/601

Planining to take a look at that later in this week. Feel free to work on this if you have time, PRs are welcome.

**Comment by mdegis** [comment]
another related issue: https://github.com/yaml/pyyaml/issues/724

**Comment by jonbwhite** [comment]
Thanks for the quick fix!
